### ISSUE TITLE
How to correctly create backstage page?

### ISSUE THREAD

**Issue by Yumeryu** [fluentribbon/Fluent.Ribbon#401]
Every fluent button, tabItem, applicationMenu I put in back stage section, can't bind any command.
Some buttons when clicked, only the back stage page closes, no command triggered. 

When I use <i:Interaction.Triggers> with BackstageTabItem, again, the command does not trigger. 

Please point me to any sample code, articles or any guide how fluent backstage control works. 

Thanks in advance. 

---
### Environment

- Fluent.Ribbon __v4.0.3.394__
- Theme __office 2010 blue__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
I can't reproduce your issue.
Could you attach a repro showing your issue?

**Comment by Yumeryu** [comment]
@batzen  Thanks for your reply. I attacked a sample. Please have a look and let me know. 


[WpfApplication1.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/833751/WpfApplication1.zip)

**Comment by batzen** [comment]
According to your repro you have only tried to wire a single command.
That one isn't working because you tried to bind to `ExitCommand` while the command property on your viewmodel is name `CommandExit`.
Changing the binding to the correct property name causes the command to work.

**Comment by Yumeryu** [comment]
Ouch, that was embarrassing. Sorry wasted your time there. 
Created the sample project as my main project now. Hopefully, this time can show the issue. 

Still the same Exit button. Please let me know if I'm doing something wrong. Thanks. 

[WpfApplication1.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/838186/WpfApplication1.zip)

**Comment by batzen** [comment]
You are trying to bind to a field which is not supported in WPF.
You have to use a property.

These kinds of errors are logged to the output window by WPF.
In your case that's:
```
System.Windows.Data Error: 40 : BindingExpression path error: 'CommandExit' property not found on 'object' ''MainViewModel' (HashCode=37138401)'. BindingExpression:Path=CommandExit; DataItem='MainViewModel' (HashCode=37138401); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
```

**Comment by batzen** [comment]
Found the issue, will be fixed in v6.0.

**Comment by batzen** [comment]
Issue is tracked in #415

**Comment by batzen** [comment]
Fixed #415 by the way.

**Comment by Yumeryu** [comment]
Thanks for the reply and quick fix. 

I have downloaded your new fix, and build a DLL for that sample project to reference. 

However, the command is still not triggered when clicking the Exit button. there is no error in output window this time, only a printed log "Dismissing Popup".

**Comment by batzen** [comment]
I should have tested a bit more. Sorry. Will finally fix it and test it. ;-)

**Comment by batzen** [comment]
As a workaround you can set `DataContext="{Binding}"` on your backstage.
The final fix will only be in 6.0.

**Comment by batzen** [comment]
Pushed and tested with your repro.
