### ISSUE TITLE
Fluent:ApplicationMenu not closing on outside click after opening context menu.

### ISSUE THREAD

**Issue by DavidPerez18** [fluentribbon/Fluent.Ribbon#663]
I created a blank window with a Fluent:ApplicationMenu for testing.

![fluentxaml](https://user-images.githubusercontent.com/25258430/48016657-27dc6080-e0fa-11e8-8f3c-a83ef5d5d131.png)

If the ApplicationMenu is opened (dropdown is opened) then normally it closes when the user clicks off the menu.
This breaks down when opening the ContextMenu (right click) in the ApplicationMenu.

![fluentwindow2](https://user-images.githubusercontent.com/25258430/48016761-72f67380-e0fa-11e8-8b54-65080ff3413f.PNG)

In this state, the only way to close the ApplicationMenu is to click on the ApplicationMenu button again.

**Comment by batzen** [comment]
This should be fixed in version 7.0. Could you try to reproduce your issue using the preview version from nuget?

**Comment by DavidPerez18** [comment]
I am using the latest stable version available to me through the nuget package manager which is v6.1.0.326. I don't see any preview versions on here. But that's okay, I can wait for the stable release whenever that comes. Thanks!

**Comment by DavidPerez18** [comment]
I have installed alpha0456 7.0 and I am still having the issue.
